- name: Add node.js apt key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add node.js repositories
  apt_repository: 
    repo: '{{ item }} https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
  with_items:
    - deb
    - deb-src

- name: Install node.js
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Install "pm2" node.js package globall
  npm: 
    name: pm2
    global: yes
    production: yes
