- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: latest
  notify: Start nginx

- name: Configure nginx reverse proxy for node.js app
  copy:
    src: nginx/sites-available/default
    dest: /etc/nginx/sites-available/
  notify: Reload nginx

- name: Configure nginx logrotate
  copy:
    src: logrotate.d/nginx
    dest: /etc/logrotate.d/

- name: Create app root directory
  file:
    dest: /var/www/app
    state: directory
  notify: Reload nginx
