- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: latest
  notify: start nginx

- name: Configure nginx reverse proxy for node.js app
  copy:
    src: default
    dest: /etc/nginx/sites-available/
  notify: restart nginx
